//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeziEntities : DbContext
    {
        public GeziEntities()
            : base("name=GeziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_AVM> Table_AVM { get; set; }
        public virtual DbSet<Table_Kategori> Table_Kategori { get; set; }
        public virtual DbSet<Table_Konser> Table_Konser { get; set; }
        public virtual DbSet<Table_Otel> Table_Otel { get; set; }
        public virtual DbSet<Table_Seyahat> Table_Seyahat { get; set; }
        public virtual DbSet<Table_Sinema> Table_Sinema { get; set; }
        public virtual DbSet<Table_TIYATRO> Table_TIYATRO { get; set; }
        public virtual DbSet<TableRestorant> TableRestorant { get; set; }
    }
}
