//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Seyahat
    {
        public int SeyahatID { get; set; }
        public string SeyahatAdı { get; set; }
        public string Seyahat_Konumu { get; set; }
        public string Seyahat_İl { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
    
        public virtual Table_Kategori Table_Kategori { get; set; }
    }
}
