//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Konser
    {
        public int KonserID { get; set; }
        public string KonserAdı { get; set; }
        public string KonserKonumu { get; set; }
        public string Konserİl { get; set; }
        public string Konserİlce { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<System.DateTime> KonserTarihi { get; set; }
    
        public virtual Table_Kategori Table_Kategori { get; set; }
    }
}
