//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjee.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRestorant
    {
        public int RestorantID { get; set; }
        public string RestorantAdı { get; set; }
        public string RestorantKonumu { get; set; }
        public string Restorantİl { get; set; }
        public string Restorantİlce { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
    
        public virtual Table_Kategori Table_Kategori { get; set; }
    }
}
